name: deploy_on_push
run-name: ${{ github.actor }} is executed this action.
on:
  push:
    branches: ["master"]
jobs:
  build_deploy_gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v1.1.1
      - name: Install Dependencies
        run: bun install
      - name: Build Project
        run: bun run build
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          bun run deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          firebase_apiKey: ${{secrets.FIREBASE_APIKEY}}
          firebase_authDomain: ${{vars.FIREBASE_AUTHDOMAIN}}
          firebase_projectId: ${{vars.FIREBASE_PROJECTID}}
          firebase_storageBucket: ${{vars.FIREBASE_STORAGEBUCKET}}
          firebase_messagingSenderId: ${{vars.FIREBASE_MESSAGINGSENDERID}}
          firebase_appId: ${{vars.FIREBASE_APPID}}
          firebase_measurementId: ${{vars.FIREBASE_MEASUREMENTID}}